manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: SethMilliken
      revision: sofle-led-strip-support
      import: app/west.yml
  self:
    path: config
